spring:
  datasource:
    dynamic:
      primary: system #设置默认的数据源或者数据源组,默认值即为master
      strict: true #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        system:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver # 驱动
          url: jdbc:mysql://127.0.0.1:3306/dd_system?useSSL=false&serverTimezone=GMT%2B8 # 连接地址
          username: root # 用户名
          password: 123 #密码
