spring:
  rabbitmq:
    host: 127.0.0.1 # 地址
    port: 5672 # 端口
    username: guest # 用户名
    password: guest # 密码
    template:
      retry:
        enabled: true # 开启发送端的重试
#    listener:
#      simple:
#        prefetch: 1
