# 专库专表 垂直分表
spring:
  shardingsphere:
    datasource:
      names: dss
      dss:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver # 驱动
        jdbc-url: jdbc:mysql://127.0.0.1:3306/sj_single?useSSL=false&serverTimezone=GMT%2B8 # 连接地址
        username: root # 用户名
        password: 123 # 密码
    rules:
      sharding:
        tables:
          employee:
            actual-data-nodes: dss.employee #指定 employee 表为单独库
            key-generate-strategy:
              column: id # 指定 employee 表里面主键列为 id
              key-generator-name: SNOWFLAKE # 指定 employee 表里面主键生成策略为 SNOWFLAKE
    props:
      sql-show: true   # 打开sql输出日志
