# 公共表
spring:
  shardingsphere:
    datasource:
      names: ds1,ds2
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver # 驱动
        jdbc-url: jdbc:mysql://127.0.0.1:3306/sj_db1?useSSL=false&serverTimezone=GMT%2B8 # 连接地址
        username: root # 用户名
        password: 123 # 密码
      ds2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver # 驱动
        jdbc-url: jdbc:mysql://127.0.0.1:3306/sj_db2?useSSL=false&serverTimezone=GMT%2B8 # 连接地址
        username: root # 用户名
        password: 123 # 密码
    rules:
      sharding:
        tables:
          city:
            key-generate-strategy:
              column: id
              key-generator-name: SNOWFLAKE
        broadcast-tables: city # 配置公共表
    props:
      sql-show: true   # 打开sql输出日志
